
name: CI Dev Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write   # 讓 workflow 可以 push / create release

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: build-artifact
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js (if needed)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build
        run: |
          npm install
          npm run build
          zip -r build.zip .  # 打包成果物

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build.zip

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Install gh CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Auth gh CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${GITHUB_TOKEN}" | gh auth login --with-token

      - name: Create Dev Release
        env:
          TAG: dev-${{ github.run_number }}
          NOTE: "${{ vars.RELEASE_NOTE || 'Dev automatic release' }}"
        run: |
          gh release create "$TAG" build.zip --notes "$NOTE" || echo "release may already exist"
