name: CI/CD Deployment Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch: # 允許手動觸發

permissions:
  contents: write  # 最低權限即可修改 repo 內容

jobs:
  # -------------------------
  # Build Job
  # -------------------------
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build project
        run: |
          # 替換成你的 build 指令
          npm install
          npm run build
          zip -r build.zip .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build.zip

  # -------------------------
  # Deploy to Dev
  # -------------------------
  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Release Dev Build
        uses: jamesives/github-activity-readme@v0.4.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          MAX_LINES: 5

  # -------------------------
  # Deploy to Staging
  # -------------------------
  deploy-staging:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Release Staging Build
        run: |
          gh release create "${{ vars.BUILD_TAG }}" build.zip \
            --notes "${{ vars.RELEASE_NOTE }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ vars.BUILD_TAG }}
          NOTE: ${{ vars.RELEASE_NOTE }}

  # -------------------------
  # Deploy to Production
  # -------------------------
  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Release Production Build
        run: |
          gh release create "${{ vars.BUILD_TAG }}" build.zip \
            --notes "${{ vars.RELEASE_NOTE }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # 使用 PAT 作為 production secret
          TAG: ${{ vars.BUILD_TAG }}
          NOTE: ${{ vars.RELEASE_NOTE }}
